version: "3.7"

services:
  react:
    image: node:16-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./react-frontend:/app
    container_name: react
    networks:
      - frontend-network

  spring-boot:
    build:
      context: ./spring-backend
      dockerfile: Dockerfile
    image: spring-backend
    ports:
      - "8080:8080"
      - "5005:5005"
    container_name: spring-boot
    restart: always
#     depends_on:
#       - database
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://plee_mysql:3306/spring_social?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#       SPRING_DATASOURCE_USERNAME: plee
#       SPRING_DATASOURCE_PASSWORD: plee
    networks:
      - backend-network
      - frontend-network

#   database:
#     image: mysql:5.7
#     environment:
#       MYSQL_USER: plee
#       MYSQL_DATABASE: spring_social
#       MYSQL_PASSWORD: plee
#       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#     volumes:
#       - "./database/spring_social/:/var/lib/mysql"
#     ports:
#       - "3306:3306"
#     container_name: plee_mysql
#     networks:
#       - backend-network

networks:
  backend-network:
  frontend-network: